Fix/separation
qbeyond/terraform-google-project pull request #1
Opened 2023-01-20 09:26 UTC by QBYMKPI

# Description

Terraform Module to create GCP Projects.

# How Has This Been Tested?

- [x] Apply & Destroy Terraform Code locally

# Checklist:

- [x] I have run tests and documented them above
- [x] I have performed a self-review of my own code
- [x] I have updated the documentation

2023-01-20 09:44 UTC, QBY-ThimoLimpert requested changes
Please add headlines and descriptions for your usage examples. You can copy them from the google generated docs in README.

Please remove the google generated docs from README.

2023-01-20 13:20 UTC, ghost requested changes

2023-01-20 13:20 UTC, ghost commented on .terraform-docs.yml
>    {{ include "examples/organization_policies/configs/boolean.yaml" }}
add the name of the file on top of the code so the user knows what to do with it. `configs/boolean.yaml`

2023-01-23 07:38 UTC, QBYMKPI commented on .terraform-docs.yml
>    {{ include "examples/organization_policies/configs/boolean.yaml" }}
Put above hcl with description

2023-01-23 09:10 UTC, QBY-ThimoLimpert approved these changes, later dismissed

2023-01-23 09:10 UTC, ghost commented on .terraform-docs.yml
> +  {{ indent 0 "#" }} Usage
```suggestion
```

2023-01-23 09:42 UTC, QBY-ThimoLimpert approved these changes

2023-01-23 09:42 UTC, merged